# Generated by Django 5.2.17 on 2026-09-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_purchaseorder_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(max_length=100, unique=True)),
                ('warehouse_id', models.IntegerField()),
                ('received_by', models.IntegerField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('received_items', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PARTIAL', 'PARTIAL'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=20)),
                ('inspection_notes', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='procurement.purchaseorder')),
            ],
        ),
    ]
